### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by MatsGustavsson** [binder-examples/appmode#3] opened 2018-01-08 21:35 UTC
Hi, thanks for a great idea - just what I had been looking for. 

However, I tried it with my notebook but I get this error which is linked to "tokens" 403 when I click the notebooklink from another pc or smartphone. From my understanding it depends on problem of authenticating the user.

So it does not really work for my purpose (having a "ready to run" live version on a web-address that you can very easily let someone play with) like "Shiny".

Have you got any suggestions and or will you develop this further?

Thanks

**Comment by yuvipanda** [comment] 2018-01-08 21:38
Sorry to hear that, and thanks for reporting it, @MatsGustavsson!

Can you tell us which URL you used and what was the exact error you got? I can't reproduce it right now on any of my browsers...

**Comment by betatim** [comment] 2018-01-09 07:10
The link to share is https://mybinder.org/v2/gh/binder-examples/appmode/master?urlpath=apps%2Findex.ipynb where the user will have to wait a moment for the app to boot, a bit like when you have a large shiny app. There is work (about to be ready) on going to make the screen users see when they click that link more friendly: https://github.com/jupyterhub/binderhub/pull/384

**Comment by MatsGustavsson** [comment] 2018-01-09 18:05
Hi Yuvi,

I just got the same question from Chris who has done the plugin for the notebook.
The URL is:https://hub.mybinder.org/hub/login?next=%2Fhub%2Fuser%2Fmatsgustavsson-finance-jupyter-l7rwx6h6%2Fapps%2FSequentialStructure.ipynb%3Fappmode_scroll%3D0

And the file it is based on is this (which also contains some JS which I used in nbviewer)
https://github.com/MatsGustavsson/finance-jupyter/blob/master/SequentialStructure.ipynb

PS: please forgive me if I forgot something elementary (Im not a python guru) 

    Il Lunedì 8 Gennaio 2018 22:38, Yuvi Panda <notifications@github.com> ha scritto:
 

 Sorry to hear that, and thanks for reporting it, @MatsGustavsson!Can you tell us which URL you used and what was the exact error you got? I can't reproduce it right now on any of my browsers...—

**Comment by choldgraf** [comment] 2018-01-09 18:09
ah ha - that is a private link for your personal binder instance - it's not a link that you can share with others. You need to share this link: https://mybinder.org/v2/gh/binder-examples/appmode/master?urlpath=apps%2Findex.ipynb (and a similarly structured link for your repo)

also just a note that I'm not the author of appmode at all :-) I just created the binder example for it

**Comment by choldgraf** [comment] 2018-01-09 18:14
hey - let's take the conversation over here: https://github.com/jupyterhub/binder/issues/58

I'll close this issue so we aren't duplicating info!

**Comment by MatsGustavsson** [comment] 2018-01-09 18:53
thanks. This looks better, but you still would have to click Trust and use the appmode. No way to get it to autorun?

Jupyter Notebook

  
|  
|   |  
Jupyter Notebook
   |  |

  |

 
 

    Il Martedì 9 Gennaio 2018 19:14, Chris Holdgraf <notifications@github.com> ha scritto:
 

 Closed #3.—

**Comment by choldgraf** [comment] 2018-01-09 19:01
see the link in the "launch binder" button in this repo: https://mybinder.org/v2/gh/binder-examples/appmode/master?urlpath=apps%2Findex.ipynb

**Comment by choldgraf** [comment] 2018-01-09 19:04
(you may need to reload the page after it loads the first time, since I think there's a bug in there somewhere :-) )

**Comment by MatsGustavsson** [comment] 2018-01-09 19:06
I don't know why my link above "jupyter notebook" does not work. In my smartphone I now get token authentication... Aaaargggghhh

Inviato da Yahoo Mail su Android 
 
  Il mar, 9 gen, 2018 alle 20:01, Chris Holdgraf<notifications@github.com> ha scritto:   
see the link in the "launch binder" button in this repo: https://mybinder.org/v2/gh/binder-examples/appmode/master?urlpath=apps%2Findex.ipynb

**Comment by choldgraf** [comment] 2018-01-09 19:08
hey - I'm not sure what link you're talking about. Just a note, you should never share a link that starts with `hub.`

**Comment by MatsGustavsson** [comment] 2018-01-09 19:11
Does not help. Still token authentication is enabled bla bla Do you mean there's a bug in my code? What happens if you click on my link.l?

Inviato da Yahoo Mail su Android 
 
  Il mar, 9 gen, 2018 alle 20:04, Chris Holdgraf<notifications@github.com> ha scritto:   
(you may need to reload the page after it loads the first time, since I think there's a bug in there somewhere :-) )

**Comment by choldgraf** [comment] 2018-01-09 19:13
please paste the link you're talking about - I wanna make sure we're on the same page :-)

**Comment by MatsGustavsson** [comment] 2018-01-09 20:43
https://hub.mybinder.org/hub/login?next=%2Fhub%2Fuser%2Fmatsgustavsson-finance-jupyter-k9iydzlu%2Fapps%2FSequentialStructure.ipynb%3Fappmode_scroll%3D1800

Inviato da Yahoo Mail su Android 
 
  Il mar, 9 gen, 2018 alle 20:13, Chris Holdgraf<notifications@github.com> ha scritto:   
please paste the link you're talking about - I wanna make sure we're on the same page :-)

**Comment by MatsGustavsson** [comment] 2018-01-09 21:17
sorry it is actually this link (the previous one was in error)
https://hub.mybinder.org/user/matsgustavsson-finance-jupyter-tysv8ca7/notebooks/SequentialStructure.ipynb
 

    Il Martedì 9 Gennaio 2018 20:13, Chris Holdgraf <notifications@github.com> ha scritto:
 

 please paste the link you're talking about - I wanna make sure we're on the same page :-)—

**Comment by MatsGustavsson** [comment] 2018-01-09 21:19
When I open it on my PC it's fine but on my smartphone it asks for password or token.
https://hub.mybinder.org/user/matsgustavsson-finance-jupyter-tysv8ca7/notebooks/SequentialStructure.ipynb

 

    Il Martedì 9 Gennaio 2018 22:17, Mats Gustavsson <mats_gustavsson@yahoo.com> ha scritto:
 

 sorry it is actually this link (the previous one was in error)
https://hub.mybinder.org/user/matsgustavsson-finance-jupyter-tysv8ca7/notebooks/SequentialStructure.ipynb
 

    Il Martedì 9 Gennaio 2018 20:13, Chris Holdgraf <notifications@github.com> ha scritto:
 

 please paste the link you're talking about - I wanna make sure we're on the same page :-)—

**Comment by betatim** [comment] 2018-01-09 21:51
The link to share the repository https://github.com/MatsGustavsson/finance-jupyter is https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/master

Once you visit that link you will be redirected to a link that looks something like: https://hub.mybinder.org/user/matsgustavsson-finance-jupyter-tysv8ca7/tree This link is not a link that you can share with anyone. It is tied to the specific launch of that repository and protected by authentication (stored in a cookie).

So for the appmode example the link to share is https://mybinder.org/v2/gh/binder-examples/appmode/master?urlpath=apps%2Findex.ipynb This will redirect you to something like https://hub.mybinder.org/user/binder-examples-appmode-u40y78c4/apps/index.ipynb. The `urlpath=...` bit in the shareable link is what causes the redirect instead of showing you the file viewer.

 If you want to redirect a user directly to a notebook in your finance-jupyter repository you would share a link like: https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/master?filepath=SequentialStructure.ipynb

**Comment by MatsGustavsson** [comment] 2018-01-09 22:05
Ok thanks slowly getting there (probably my age;-) but:
1 if I click https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/master

I get to my repository which contains two ipynb files - do I need to keep only the one rendered in my binder? In my case the... Sequential...?

2. When in the repository : I click the file which has been "bound" by my binder (the ...sequential...ipynb it opens in a notebook (great) but with an ugly difference to your example: I have to trust the notebook and click on the appmode button whereas yours worked directly! Why?
3. I still cannot find the shareable link ( the one with the urlpath... Stuff inside. Where does it show?
Sorry for buggering and for writing from a phone...M

Inviato da Yahoo Mail su Android 
 
  Il mar, 9 gen, 2018 alle 22:51, Tim Head<notifications@github.com> ha scritto:   
The link to share the repository https://github.com/MatsGustavsson/finance-jupyter is https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/master

Once you visit that link you will be redirected to a link that looks something like: https://hub.mybinder.org/user/matsgustavsson-finance-jupyter-tysv8ca7/tree This link is not a link that you can share with anyone. It is tied to the specific launch of that repository and protected by authentication (stored in a cookie).

So for the appmode example the link to share is https://mybinder.org/v2/gh/binder-examples/appmode/master?urlpath=apps%2Findex.ipynb This will redirect you to something like https://hub.mybinder.org/user/binder-examples-appmode-u40y78c4/apps/index.ipynb. The urlpath=... bit in the shareable link is what causes the redirect instead of showing you the file viewer.

**Comment by choldgraf** [comment] 2018-01-09 22:27
The difference is in the URL itself. This is the "basic" binder link:

 https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/master

and if you want to enable / use the "appmode" plugin, you add the following to the end:

`?urlpath=apps/SequentialStructure.ipynb`

so the full url would be:

https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/master?urlpath=apps/SequentialStructure.ipynb
  

again to reiterate, the URLs that begin with `hub.` **will not work on any other computer**. They are unique to the computer that "clicked" on the binder link. If you want to open a Binder repo on a different computer/phone/etc, you need to click one of the two links in this response.

**Comment by MatsGustavsson** [comment] 2018-01-10 07:44
wow thanks a lot Chris it works- (like magic I have to confess, is there somewhere I ca read upp on what this "urlpath=apps" does)?
also a final question what happens if more than one users click on the link simulatienopusly (do they have separate instances, we get crashes or whatever)?
Cheers from Milan
 

    Il Martedì 9 Gennaio 2018 23:27, Chris Holdgraf <notifications@github.com> ha scritto:
 

 The difference is in the URL itself. This is the "basic" binder link:https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/masterand if you want to enable / use the "appmode" plugin, you add the following to the end:?urlpath=apps/SequentialStructure.ipynbso the full length would be:https://mybinder.org/v2/gh/MatsGustavsson/finance-jupyter/master?urlpath=apps/SequentialStructure.ipynb—

**Comment by choldgraf** [comment] 2018-01-10 16:18
urlpath is a parameter that BinderHub knows how to use - it basically just changes whatever comes after the address of your Binder instance (replacing `/tree` with whatever else). In this case appmode has been enable to be easily accessible via the url so it works here!

Also if multiple people click a binder link two totally different binder instances will be created for them, so no worries there!

(gonna close this issue since I think the original problem has been resolved!)

**Closed as completed by choldgraf** 2018-01-10 16:18 UTC
